spring.application.name=nutrishare-backend
server.port=9003
spring.data.mongodb.uri=mongodb://localhost:27017/nutricion

# JWT Configuration
jwt.secret=super-secret-key-for-jwt-signing-32bytes
jwt.expiration-days=14
