spring.application.name=nutrishare-backend
server.port=9003
spring.data.mongodb.uri=mongodb://localhost:27017/nutricion

# JWT Configuration
jwt.secret=super-secret-key-for-jwt-signing-32bytes
jwt.expiration-days=14

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
